name: Run govulncheck on Go Code

on:
  push:
    branches:
      - main
      - v2
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/vulncheck.yml'

  pull_request:
    branches:
      - main
      - v2
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/vulncheck.yml'

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
          cache: true

      - name: Install Govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run Govulncheck Scan
        run: govulncheck ./...
